In [1]:
import numpy as np
a = np.random.rand(5)

In [2]:
print(a)

[0.36896823 0.00831768 0.27120162 0.06732635 0.33615966]


In [3]:
print(a.T)

[0.36896823 0.00831768 0.27120162 0.06732635 0.33615966]


In [4]:
dot_product = np.dot(a , a.T)

In [5]:
print(dot_product)

0.32729320982268173


In [6]:
a = np.random.rand(5,1)
print(a)

[[0.66697784]
 [0.06808158]
 [0.84624898]
 [0.09044473]
 [0.31165082]]


In [7]:
print(a.T)

[[0.66697784 0.06808158 0.84624898 0.09044473 0.31165082]]


In [8]:
print(np.dot(a , a.T))

[[0.44485944 0.0454089  0.56442932 0.06032463 0.20786419]
 [0.0454089  0.0046351  0.05761397 0.00615762 0.02121768]
 [0.56442932 0.05761397 0.71613734 0.07653876 0.26373419]
 [0.06032463 0.00615762 0.07653876 0.00818025 0.02818717]
 [0.20786419 0.02121768 0.26373419 0.02818717 0.09712623]]


In [9]:
print('NICE')

NICE


In [10]:
a = np.random.rand(1,5) 
print(a.shape)

(1, 5)


In [11]:
a = np.random.rand(3,4) 
b = np.random.rand(1,4)
c = a + b 
print(c)

[[1.43748845 1.75177038 1.62747457 0.45127346]
 [0.86036888 1.02720761 0.76918066 1.37781356]
 [0.94576555 0.98881598 1.07373791 0.90164003]]


In [16]:
a = np.random.rand(4,3) 
b = np.random.rand(1,3)
c = a * b 
print(c)

[[0.03057665 0.13463289 0.08369846]
 [0.0466427  0.15975864 0.39425094]
 [0.04841245 0.47018137 0.41296748]
 [0.04770106 0.31734686 0.20973977]]


In [17]:
a = np.array([[2,1] , [1,3]])
print(np.dot(a,a))

[[ 5  5]
 [ 5 10]]
