In [10]:
import math

# GRADED FUNCTION: basic_sigmoid

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    s = 1. /(1+ math.exp(-x))
    
    # YOUR CODE ENDS HERE
    
    return s

In [11]:
print("basic_sigmoid(1) = " + str(basic_sigmoid(1)))

# basic_sigmoid_test(basic_sigmoid)

basic_sigmoid(1) = 0.7310585786300049


In [12]:
import numpy as np
image = np.random.rand(3,3,2)
print(image)
print(image.shape[0])


[[[0.50201865 0.69264949]
  [0.08485031 0.50626262]
  [0.88536953 0.20880168]]

 [[0.42983055 0.45172452]
  [0.55696264 0.84888713]
  [0.44460157 0.34303263]]

 [[0.5025521  0.77359703]
  [0.27208457 0.64730182]
  [0.13541119 0.2139217 ]]]
3


In [13]:
print(image.shape[1])
print(image.shape[2])


3
2


THE CORRECT FORMAT FOR THE RESHAPE IS THE BELOW FORM DO REMEMBER IT 


In [17]:
v = np.reshape(image , (image.shape[0]*image.shape[1]*image.shape[2] , 1))

In [18]:
print(v)

[[0.50201865]
 [0.69264949]
 [0.08485031]
 [0.50626262]
 [0.88536953]
 [0.20880168]
 [0.42983055]
 [0.45172452]
 [0.55696264]
 [0.84888713]
 [0.44460157]
 [0.34303263]
 [0.5025521 ]
 [0.77359703]
 [0.27208457]
 [0.64730182]
 [0.13541119]
 [0.2139217 ]]


In [2]:
# GRADED FUNCTION: softmax

def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (m,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    
    #(≈ 3 lines of code)
    # Apply exp() element-wise to x. Use np.exp(...).
    # x_exp = ...

    # Create a vector x_sum that sums each row of x_exp. Use np.sum(..., axis = 1, keepdims = True).
    # x_sum = ...
    
    # Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
    # s = ...
    
    # YOUR CODE STARTS HERE
    x_exp = np.exp(x) ; 
    x_sum = np.sum(x , axis = 1 , keepdims = True)
    s = x_exp/x_sum
    
    # YOUR CODE ENDS HERE
    
    return s

In [3]:
import numpy as np
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(t_x)))

softmax(x) = [[5.06442745e+02 4.61816006e-01 9.27582244e+00 6.25000000e-02
  6.25000000e-02]
 [9.13860965e+01 1.23677633e+01 8.33333333e-02 8.33333333e-02
  8.33333333e-02]]
